### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by akvadrako** [rtfd/commonmark.py#96]
Is there any?

**Comment by nikolas** [comment]
We have sphinx / readthedocs set up here: https://commonmark-py.readthedocs.io/en/latest/index.html

It looks like the actual API documentation there isn't working correctly. Thanks for the reminder, we need to fix this.

**Comment by bradwood** [comment]
Hi... This is still down like a year later...   Can you fix pls?

**Comment by nikolas** [comment]
Working now, though they are kind of sparse: https://commonmarkpy.readthedocs.io/en/latest/api.html
